### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by MerBik** [idolize/xcloud-keyboard-mouse#68] opened 2022-09-18 22:38 UTC
### Bug description

Error: "IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)"

### Extension Version

Version 2.6

### What browser(s) are you seeing the problem on?

Chrome

**Comment by idolize** [comment] 2022-10-03 22:51
Duplicate of https://github.com/idolize/xcloud-keyboard-mouse/issues/68

**Closed by idolize** 2022-10-03 22:51 UTC
Labels: bug, triage
