### ISSUE TITLE
stop recognizing the games

### ISSUE THREAD

**Issue by MrSac0la** [idolize/xcloud-keyboard-mouse#54] opened 2022-06-27 14:42 UTC
### Bug description

this extension is not working when enter in any game it just dont recognize that im in the xcloud or out and dont work
![bug](https://user-images.githubusercontent.com/93526732/175967658-15238ef9-8f8b-438b-8bef-09d62337542c.png)
and is basically that just dont want to work and i cant play without this pls help me

### Extension Version

Keyboard & Mouse For Xbox Xcloud

### What browser(s) are you seeing the problem on?

Chrome

**Comment by idolize** [comment] 2022-10-03 23:43
I was trying to make it so the extension does not run at all except on xcloud, and with Chrome's new Manifest V3 and the changes to the way the "browserAction" button/popup work makes it a bit buggy to activate properly at times (you can usually fix it by just relaunching Chrome).

This issue should be completely fixed in the next version (3.0) of the extension I will be pushing out shortly as well.

**Comment by idolize** [comment] 2022-10-03 23:46
Duplicate of #34

**Closed by idolize** 2022-10-03 23:46 UTC
Labels: bug
