### ISSUE TITLE
DRIFTY AS HECK

### ISSUE THREAD

**Issue by Beenz101** [idolize/xcloud-keyboard-mouse#62] opened 2022-09-05 14:11 UTC
### Bug description

feels like using a Nintendo Switch how drifty it is, and no it's not my mouse. please make it smoother on the right stick.

### Extension Version

e

### What browser(s) are you seeing the problem on?

Chrome

### Browser version number

full version

**Comment by idolize** [comment] 2022-10-03 23:49
Duplicate of https://github.com/idolize/xcloud-keyboard-mouse/issues/48 and https://github.com/idolize/xcloud-keyboard-mouse/issues/47

> Try increasing the stick sensitivity in game and lower the sensitivity in the extension profile - it actually works much better. I just didn't want to make this the default, as it's not possible for me to automatically adjust the in-game settings on behalf of the user.

**Closed by idolize** 2022-10-03 23:49 UTC
Labels: bug, triage
