### ISSUE TITLE
Occasionally not opening/registering

### ISSUE THREAD

**Issue by AzshbknaegtvJNL** [idolize/xcloud-keyboard-mouse#61] opened 2022-08-30 10:10 UTC
### Bug description

When i try to use it with cloud gaming, it just says that i am playing ''none'' even when im trying to play a game.

### Extension Version

2.6

### What browser(s) are you seeing the problem on?

Chrome

**Comment by idolize** [comment] 2022-10-03 23:43
I was trying to make it so the extension does not run at all except on xcloud, and with Chrome's new Manifest V3 and the changes to the way the "browserAction" button/popup work makes it a bit buggy to activate properly at times (you can usually fix it by just relaunching Chrome).

This issue should be completely fixed in the next version (3.0) of the extension I will be pushing out shortly as well.

**Comment by idolize** [comment] 2022-10-03 23:46
Duplicate of #34

**Closed by idolize** 2022-10-03 23:46 UTC
Labels: bug
