### ISSUE TITLE
I'm having mouse problems in Kiwi Browser 

### ISSUE THREAD

**Issue by Oxdf22** [idolize/xcloud-keyboard-mouse#74] opened 2022-10-08 17:33 UTC
### Bug description

I tried in several ways to activate the mouse but I couldn't 

### Extension Version

3.0

### What browser(s) are you seeing the problem on?

Other (Please specify)

### Other browser

Kiwi Browser Android

**Comment by Oxdf22** [comment] 2022-10-08 17:34
![Uploading Screenshot_20221008-143054.png…]()

**Comment by Oxdf22** [comment] 2022-10-08 17:36
![Screenshot_20221008-143054](https://user-images.githubusercontent.com/115331193/194720367-a6b949ac-af4e-4f21-a472-9a48069144be.png)

**Comment by idolize** [comment] 2022-10-15 00:48
Duplicate of #20

**Closed by idolize** 2022-10-15 00:48 UTC
Labels: bug, triage
