### ISSUE TITLE
Keyboard and Mouse Issue on Android using Kiwi browser.

### ISSUE THREAD

**Issue by RobCKnight** [idolize/xcloud-keyboard-mouse#71] opened 2022-10-05 21:23 UTC
### Bug description

Hi,

The extension installs and the keyboard bit works but I get a message in the middle of the browser window saying click here again to enable?

I can confirm that when in the menu, the keyboard functions are working.

I am using Samsung DeX on a Samsung Android device with a monitor, keyboard and mouse and the Kiwi browser + Chrome Extension.

When in the Game Pad tester, I can see that clicking left right mouse buttons replicate the fire buttons on the controller.

Any ideas/help to get the mouse working?

May thanks,

Rob.

### Extension Version

2.6

### What browser(s) are you seeing the problem on?

Other (Please specify)

### Other browser

Kiwi for Android

### Browser version number

Latest from Play Store

**Comment by idolize** [comment] 2022-10-15 00:48
Duplicate of #20

**Closed by idolize** 2022-10-15 00:48 UTC
Labels: bug, triage
