### ISSUE TITLE
Mouse doesn't want to work in Xcloud

### ISSUE THREAD

**Issue by Hikeenn** [idolize/xcloud-keyboard-mouse#59] opened 2022-08-18 21:54 UTC
### Bug description

When I enter a game and I click the mouse button to activate the mouse in the game, nothing happens and I can't use the mouse to control the camera for example, I've tried everything and I can't solve

(I'm trying to do this on mobile)

### Extension Version

2.6

### What browser(s) are you seeing the problem on?

Other (Please specify)

### Other browser

Kiwi Browser

**Comment by Dabithor** [comment] 2022-09-23 08:40
I am also having this issue; it seems the extension cannot take control of the mouse as my Tablet recognizes it as basically a finger for the touch controls. I am using Kiwi browser on a Samsung Tab S7+

**Comment by idolize** [comment] 2022-10-03 23:40
Duplicate of https://github.com/idolize/xcloud-keyboard-mouse/issues/8

**Closed by idolize** 2022-10-03 23:40 UTC
Labels: bug, triage
